[project]
name = "sample-valkey-app"
version = "1.0.1"
description = "Sample web server using Valkey"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.0.3",
    "valkey>=6.0.2",
]
